### ISSUE TITLE
데이터 누락

### ISSUE THREAD

**Issue by SerenityS** [pumgall/pumgall_front#2]
안녕하세요.

이번에 개인 프로젝트를 위한 채보 데이터들을 수집하기 위하여 공식 홈페이지에서 일차적으로 파싱한 후
누락된 곡이나 채보가 없는지를 확인하기 위하여 타 사이트들과 교차검증을 하는 과정에서
공식 홈페이지의 데이터에 여러 결함이 있음을 발견하였고,
데이터 소스가 공식 홈페이지로 추정되는 본 Repo에서도 비슷한 문제점들이 발견되어 Issue 문의합니다.

1. 우편마차 영문 오탈자
songNo : 50
ikos Post -> Csikos Post

2. 앨범 자켓 미일치
songNo : 2, 3, 4

3. 공식 홈페이지 기준 채보가 누락된 곡들
songNo : 22, 44, 55, 57, 65, 83, 95, 114, 115, 125, 128, 135, 137, 138, 165, 168, 175, 230, 234, 235, 237, 239, 240, 248, 249, 260, 261, 262, 274, 275, 276, 319, 321, 323, 327, 328, 329, 331, 332, 334, 353, 360, 362, 366, 373, 381, 520, 3946, 7458

**Comment by daebo01** [comment]
안녕하세요.

1. 수정 완료
2. 수정 완료
3. 240, 276 -> 위키에 데이터가 없음, 520, 3946 -> 위키랑 데이터 일치, 그 외에는 수정 완료되었습니다

제보 감사드립니다.

**Comment by SerenityS** [comment]
240 : DP03 - KAZEMURA
276 : DP03 - KAZEMURA
520 : D17 - SUNNY
3946 : DP04 - DR.BOX

해당 위키가 어디인지는 잘 모르겠으나 정보의 신뢰성에 의심이 갑니다...

**Comment by SerenityS** [comment]
제 프로젝트 구조에 맞춰 파싱한 JSON은 https://gist.github.com/SerenityS/80e1c69f76961950c21fad949bed454b에 공개되어있으며... 펌프 데이터 사이트로는 https://pumpout2.anyhowstep.com:17593를 추천드립니다.

**Comment by daebo01** [comment]
주신 데이터 반영하였습니다
감사합니다
